//! JNI boundary for `ai.choosh.NativeBridge`. Every native method here is a
//! thin marshaling wrapper (string in, string out, or a handle) around
//! [`engine::Engine`] — no relay/`WebAuthn` logic lives in this file, only
//! JSON string round-tripping and the opaque-handle registry below.
//!
//! Every export uses fixed-width integers or `JString` only. No raw
//! pointer crosses the ABI: `nativeInit` returns a small integer handle,
//! looked up in a process-global registry, not a transmuted `Box` pointer —
//! the same discipline the crate this replaces used, for the same reason
//! (a raw handle-as-pointer is one JNI misuse away from real memory
//! corruption; an integer lookup key isn't).

#![allow(unsafe_code)] // Required only for Edition 2024's `no_mangle` ABI attribute, generated by `native_method!` below.

mod engine;
mod http_lite;
mod markdown_gateway;
mod terminal_renderer;
mod web_gateway;
#[cfg(target_os = "android")]
mod gateway_jni;
#[cfg(target_os = "android")]
mod terminal_jni;
#[cfg(feature = "dev-passkey")]
mod dev_passkey;

use engine::Engine;
use jni::objects::{JClass, JString};
use jni::sys::{jboolean, jlong};
use jni::{Env, native_method};
use std::collections::HashMap;
use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::{Arc, LazyLock, Mutex};
use tokio::runtime::Runtime;

struct EngineHandle {
    engine: Arc<Engine>,
    runtime: Runtime,
}

static ENGINES: LazyLock<Mutex<HashMap<i64, EngineHandle>>> = LazyLock::new(|| Mutex::new(HashMap::new()));
static NEXT_HANDLE: AtomicI64 = AtomicI64::new(1);

fn error_json(message: &str) -> String {
    serde_json::json!({ "error": message }).to_string()
}

fn jstring_to_string(env: &Env<'_>, value: &JString<'_>) -> Result<String, jni::errors::Error> {
    Ok(value.mutf8_chars(env)?.to_string())
}

fn with_handle<T>(handle: jlong, absent: T, present: impl FnOnce(&EngineHandle) -> T) -> T {
    let engines = ENGINES.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
    engines.get(&handle).map_or(absent, present)
}

/// Lets `terminal_jni.rs` reach the single shared [`engine::Engine`]/
/// `PhoneConnection` behind a connection handle to open a PTY tunnel,
/// reusing `Engine::open_pty_tunnel` rather than opening a second
/// `PhoneConnection`. Not exposed outside this crate.
#[cfg(target_os = "android")]
pub(crate) fn with_connection_engine<T>(handle: jlong, present: impl FnOnce(&Engine, &Runtime) -> T) -> Option<T> {
    let engines = ENGINES.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
    engines.get(&handle).map(|h| present(&h.engine, &h.runtime))
}

/// Like [`with_connection_engine`], but returns a cloned `Arc<Engine>`
/// instead of handing a borrow into a synchronous closure — what
/// `gateway_jni.rs` needs, since a gateway's per-connection `opener`
/// closures call `Engine` methods from *their own* async tasks (potentially
/// running on a different `Runtime` than the connection's own), where
/// re-entering the connection's `Runtime` via `block_on` would panic
/// ("Cannot start a runtime from within a runtime"). `Engine`'s own methods
/// only touch runtime-agnostic `tokio::sync` primitives internally (see
/// `PhoneConnection`'s module docs), so calling them directly from any
/// runtime context is safe — no `block_on` needed here at all.
#[cfg(target_os = "android")]
pub(crate) fn connection_engine_arc(handle: jlong) -> Option<Arc<Engine>> {
    let engines = ENGINES.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
    engines.get(&handle).map(|h| Arc::clone(&h.engine))
}

// `native_method!`'s generated wrapper calls these implementation functions
// with the exact `JString` (by-value) parameter types declared in the
// macro invocations below — narrowing these to `&JString` would mismatch
// that generated call site, so the by-value params clippy would otherwise
// flag here are load-bearing, not an oversight.
#[allow(clippy::needless_pass_by_value)]
fn native_init<'local>(env: &mut Env<'local>, _class: JClass<'local>, http_base_url: JString<'local>, ws_url: JString<'local>) -> Result<jlong, jni::errors::Error> {
    let http_base_url = jstring_to_string(env, &http_base_url)?;
    let ws_url = jstring_to_string(env, &ws_url)?;
    let Ok(runtime) = Runtime::new() else {
        // No handle to return that would make this recoverable from
        // Kotlin's side in a meaningful way — a failed OS thread-pool
        // creation is not something a retry fixes. Every other native
        // method here treats "handle not found" the same as "engine
        // failed to initialize", so returning 0 is safe and consistent.
        return Ok(0);
    };
    let engine = Arc::new(Engine::new(http_base_url, ws_url));
    let handle = NEXT_HANDLE.fetch_add(1, Ordering::Relaxed);
    ENGINES
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
        .insert(handle, EngineHandle { engine, runtime });
    Ok(handle)
}

fn native_webauthn_register_start<'local>(env: &mut Env<'local>, _class: JClass<'local>, handle: jlong) -> Result<JString<'local>, jni::errors::Error> {
    let body = with_handle(handle, error_json("unknown engine handle"), |h| h.runtime.block_on(h.engine.webauthn_register_start()));
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_webauthn_register_finish<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    credential_json: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let credential_json = jstring_to_string(env, &credential_json)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.webauthn_register_finish(&credential_json))
    });
    JString::new(env, body)
}

fn native_webauthn_login_start<'local>(env: &mut Env<'local>, _class: JClass<'local>, handle: jlong) -> Result<JString<'local>, jni::errors::Error> {
    let body = with_handle(handle, error_json("unknown engine handle"), |h| h.runtime.block_on(h.engine.webauthn_login_start()));
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_webauthn_login_finish<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    credential_json: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let credential_json = jstring_to_string(env, &credential_json)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.webauthn_login_finish(&credential_json))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_connect<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    session_credential: JString<'local>,
) -> Result<jboolean, jni::errors::Error> {
    let session_credential = jstring_to_string(env, &session_credential)?;
    let connected = with_handle(handle, false, |h| h.runtime.block_on(h.engine.connect(&session_credential)));
    Ok(jboolean::from(connected))
}

fn native_list_devhosts<'local>(env: &mut Env<'local>, _class: JClass<'local>, handle: jlong) -> Result<JString<'local>, jni::errors::Error> {
    let body = with_handle(handle, error_json("unknown engine handle"), |h| h.runtime.block_on(h.engine.list_devhosts()));
    JString::new(env, body)
}

// `fcm_token` must stay `JString<'local>` by value to match the exact
// signature `native_method!`'s macro expects below (mirroring
// `native_connect`'s `session_credential` and `native_webauthn_*`'s
// `credential_json`, both the identical by-value-then-borrow shape) — the
// lint's own suggested fix (`&JString<'local>`) isn't a safe substitution
// here, since it's the macro-generated JNI wrapper's argument type this
// has to match, not a normal Rust call site clippy can freely rewrite.
#[allow(clippy::needless_pass_by_value)]
fn native_register_fcm_token<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    fcm_token: JString<'local>,
) -> Result<jboolean, jni::errors::Error> {
    let fcm_token = jstring_to_string(env, &fcm_token)?;
    let registered = with_handle(handle, false, |h| h.runtime.block_on(h.engine.register_fcm_token(&fcm_token)));
    Ok(jboolean::from(registered))
}

// `target_device_id`/`workspace_id`/`from`/`to` all stay `JString<'local>` by
// value to match `native_method!`'s macro-generated wrapper's exact
// signature — see `native_init`'s comment. `from`/`to` empty means "field
// omitted", per `Engine::workspace_diff`'s `none_if_empty` doc comment;
// Kotlin passes `""` for `null`.
#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_workspace_diff<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    from: JString<'local>,
    to: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let from = jstring_to_string(env, &from)?;
    let to = jstring_to_string(env, &to)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_diff(&target_device_id, &workspace_id, &from, &to))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_workspace_log<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    revset: JString<'local>,
    limit: jlong,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let revset = jstring_to_string(env, &revset)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_log(&target_device_id, &workspace_id, &revset, limit))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_workspace_op_log<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    limit: jlong,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_op_log(&target_device_id, &workspace_id, limit))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_workspace_op_undo<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    op_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let op_id = jstring_to_string(env, &op_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_op_undo(&target_device_id, &workspace_id, &op_id))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_workspace_op_restore<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    op_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let op_id = jstring_to_string(env, &op_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_op_restore(&target_device_id, &workspace_id, &op_id))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_workspace_status<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_status(&target_device_id, &workspace_id))
    });
    JString::new(env, body)
}

// `target_device_id` stays `JString<'local>` by value to match
// `native_method!`'s macro-generated wrapper — see `native_init`'s comment.
#[allow(clippy::needless_pass_by_value)]
fn native_workspace_list<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| h.runtime.block_on(h.engine.workspace_list(&target_device_id)));
    JString::new(env, body)
}

// `target_device_id`/`workspace_id`/`path_prefix`/`revision`/`cursor` all
// stay `JString<'local>` by value to match `native_method!`'s
// macro-generated wrapper — see `native_init`'s comment. Empty
// `revision`/`cursor` means "omitted", per `Engine::workspace_tree_list`'s
// `none_if_empty` convention; Kotlin passes `""` for `null`.
#[allow(clippy::needless_pass_by_value)]
#[allow(clippy::too_many_arguments)] // matches the RPC's own field count, same posture as native_save_document
fn native_workspace_tree_list<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    path_prefix: JString<'local>,
    revision: JString<'local>,
    cursor: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let path_prefix = jstring_to_string(env, &path_prefix)?;
    let revision = jstring_to_string(env, &revision)?;
    let cursor = jstring_to_string(env, &cursor)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.workspace_tree_list(&target_device_id, &workspace_id, &path_prefix, &revision, &cursor))
    });
    JString::new(env, body)
}

// `target_device_id`/`workspace_id`/`path` all stay `JString<'local>` by
// value to match `native_method!`'s macro-generated wrapper — see
// `native_init`'s comment.
#[allow(clippy::needless_pass_by_value)]
fn native_open_document<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    path: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let path = jstring_to_string(env, &path)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.open_document(&target_device_id, &workspace_id, &path))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
#[allow(clippy::too_many_arguments)] // matches the RPC's own field count; splitting this would just move the arity elsewhere
fn native_save_document<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    path: JString<'local>,
    base_revision: JString<'local>,
    content_base64: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let path = jstring_to_string(env, &path)?;
    let base_revision = jstring_to_string(env, &base_revision)?;
    let content_base64 = jstring_to_string(env, &content_base64)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.save_document(&target_device_id, &workspace_id, &path, &base_revision, &content_base64))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_item_list<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.item_list(&target_device_id, &workspace_id))
    });
    JString::new(env, body)
}

// `target_device_id`/`workspace_id`/`item_type`/`name`/`agent`/`command_json`
// all stay `JString<'local>` by value to match `native_method!`'s
// macro-generated wrapper — see `native_init`'s comment. Empty
// `agent`/`command_json` means "omitted"; `port <= 0` means "omitted" — see
// `Engine::item_create`'s doc comment for the full field-by-field contract.
#[allow(clippy::needless_pass_by_value)]
#[allow(clippy::too_many_arguments)] // matches the RPC's own field count, same posture as native_save_document
fn native_item_create<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    item_type: JString<'local>,
    name: JString<'local>,
    agent: JString<'local>,
    command_json: JString<'local>,
    port: jlong,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let item_type = jstring_to_string(env, &item_type)?;
    let name = jstring_to_string(env, &name)?;
    let agent = jstring_to_string(env, &agent)?;
    let command_json = jstring_to_string(env, &command_json)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.item_create(&target_device_id, &workspace_id, &item_type, &name, &agent, &command_json, port))
    });
    JString::new(env, body)
}

// `target_device_id` stays `JString<'local>` by value to match
// `native_method!`'s macro-generated wrapper — see `native_init`'s comment.
#[allow(clippy::needless_pass_by_value)]
fn native_project_list<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.project_list(&target_device_id))
    });
    JString::new(env, body)
}

#[allow(clippy::needless_pass_by_value)] // see native_init's comment
fn native_project_set_primary_workspace<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    project_id: JString<'local>,
    workspace_id: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let project_id = jstring_to_string(env, &project_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.project_set_primary_workspace(&target_device_id, &project_id, &workspace_id))
    });
    JString::new(env, body)
}

/// Drains every live agent-event push received since the last call — see
/// `engine::Engine::poll_agent_events`'s doc comment for the JSON shape.
/// Kotlin is expected to call this on a timer (or whenever it's convenient
/// to check), the same "Kotlin polls, native returns current state" shape
/// every other native method here already uses — see `docs/specs/agent-events.md`.
fn native_poll_agent_events<'local>(env: &mut Env<'local>, _class: JClass<'local>, handle: jlong) -> Result<JString<'local>, jni::errors::Error> {
    let body = with_handle(handle, "[]".to_string(), |h| h.runtime.block_on(h.engine.poll_agent_events()));
    JString::new(env, body)
}

// `target_device_id`/`workspace_id` stay `JString<'local>` by value to
// match `native_method!`'s macro-generated wrapper — see `native_init`'s
// comment.
#[allow(clippy::needless_pass_by_value)]
fn native_agent_events_resume<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    handle: jlong,
    target_device_id: JString<'local>,
    workspace_id: JString<'local>,
    after_sequence: jlong,
) -> Result<JString<'local>, jni::errors::Error> {
    let target_device_id = jstring_to_string(env, &target_device_id)?;
    let workspace_id = jstring_to_string(env, &workspace_id)?;
    let body = with_handle(handle, error_json("unknown engine handle"), |h| {
        h.runtime.block_on(h.engine.agent_events_resume(&target_device_id, &workspace_id, after_sequence))
    });
    JString::new(env, body)
}

/// Fulfills a `WebAuthn` registration ceremony in-process via
/// [`dev_passkey::register`] instead of Android's platform Credential
/// Manager — see that module's doc comment for the full "debug builds
/// only, never weakens `relayd`'s verification" reasoning. Takes no engine
/// handle: unlike every other native method here, this needs no live
/// relay connection, just the relay's own HTTP origin (already known to
/// Kotlin as `BuildConfig.CHOOSH_RELAYD_HTTP_URL`, passed straight
/// through rather than plumbed through an `Engine`) and the creation
/// options JSON `Engine::webauthn_register_start` already returned.
// `origin`/`creation_options_json` stay `JString<'local>` by value to match
// `native_method!`'s macro-generated wrapper — see `native_init`'s comment.
#[cfg(feature = "dev-passkey")]
#[allow(clippy::needless_pass_by_value)]
fn native_dev_passkey_register<'local>(
    env: &mut Env<'local>,
    _class: JClass<'local>,
    origin: JString<'local>,
    creation_options_json: JString<'local>,
) -> Result<JString<'local>, jni::errors::Error> {
    let origin = jstring_to_string(env, &origin)?;
    let creation_options_json = jstring_to_string(env, &creation_options_json)?;
    let body = dev_passkey::register(&origin, &creation_options_json).unwrap_or_else(|message| error_json(&message));
    JString::new(env, body)
}

// `native_method!`'s non-raw mode always expects a `Result` return (it's
// what gives every other native method here panic-safety and Java
// exception translation for free) even though this particular method never
// produces an `Err` — dropping the wrapper here would mismatch the `-> void`
// macro invocation below, which expands to expect `Result<(), Error>`.
#[allow(clippy::unnecessary_wraps)]
fn native_close<'local>(_env: &mut Env<'local>, _class: JClass<'local>, handle: jlong) -> Result<(), jni::errors::Error> {
    if let Some(removed) = ENGINES.lock().unwrap_or_else(std::sync::PoisonError::into_inner).remove(&handle) {
        removed.runtime.block_on(removed.engine.close());
    }
    Ok(())
}

const _INIT: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_init(http_base_url: JString, ws_url: JString) -> jlong,
    fn = native_init,
};
const _REGISTER_START: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_webauthn_register_start(handle: jlong) -> JString,
    fn = native_webauthn_register_start,
};
const _REGISTER_FINISH: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_webauthn_register_finish(handle: jlong, credential_json: JString) -> JString,
    fn = native_webauthn_register_finish,
};
const _LOGIN_START: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_webauthn_login_start(handle: jlong) -> JString,
    fn = native_webauthn_login_start,
};
const _LOGIN_FINISH: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_webauthn_login_finish(handle: jlong, credential_json: JString) -> JString,
    fn = native_webauthn_login_finish,
};
const _CONNECT: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_connect(handle: jlong, session_credential: JString) -> jboolean,
    fn = native_connect,
};
const _LIST_DEVHOSTS: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_list_devhosts(handle: jlong) -> JString,
    fn = native_list_devhosts,
};
const _CLOSE: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_close(handle: jlong) -> void,
    fn = native_close,
};
const _REGISTER_FCM_TOKEN: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_register_fcm_token(handle: jlong, fcm_token: JString) -> jboolean,
    fn = native_register_fcm_token,
};
const _WORKSPACE_DIFF: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_diff(handle: jlong, target_device_id: JString, workspace_id: JString, from: JString, to: JString) -> JString,
    fn = native_workspace_diff,
};
const _WORKSPACE_LOG: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_log(handle: jlong, target_device_id: JString, workspace_id: JString, revset: JString, limit: jlong) -> JString,
    fn = native_workspace_log,
};
const _WORKSPACE_OP_LOG: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_op_log(handle: jlong, target_device_id: JString, workspace_id: JString, limit: jlong) -> JString,
    fn = native_workspace_op_log,
};
const _WORKSPACE_OP_UNDO: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_op_undo(handle: jlong, target_device_id: JString, workspace_id: JString, op_id: JString) -> JString,
    fn = native_workspace_op_undo,
};
const _WORKSPACE_OP_RESTORE: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_op_restore(handle: jlong, target_device_id: JString, workspace_id: JString, op_id: JString) -> JString,
    fn = native_workspace_op_restore,
};
const _WORKSPACE_STATUS: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_status(handle: jlong, target_device_id: JString, workspace_id: JString) -> JString,
    fn = native_workspace_status,
};
const _OPEN_DOCUMENT: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_open_document(handle: jlong, target_device_id: JString, workspace_id: JString, path: JString) -> JString,
    fn = native_open_document,
};
const _SAVE_DOCUMENT: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_save_document(handle: jlong, target_device_id: JString, workspace_id: JString, path: JString, base_revision: JString, content_base64: JString) -> JString,
    fn = native_save_document,
};
const _ITEM_LIST: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_item_list(handle: jlong, target_device_id: JString, workspace_id: JString) -> JString,
    fn = native_item_list,
};
const _ITEM_CREATE: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_item_create(handle: jlong, target_device_id: JString, workspace_id: JString, item_type: JString, name: JString, agent: JString, command_json: JString, port: jlong) -> JString,
    fn = native_item_create,
};
const _WORKSPACE_LIST: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_list(handle: jlong, target_device_id: JString) -> JString,
    fn = native_workspace_list,
};
const _WORKSPACE_TREE_LIST: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_workspace_tree_list(handle: jlong, target_device_id: JString, workspace_id: JString, path_prefix: JString, revision: JString, cursor: JString) -> JString,
    fn = native_workspace_tree_list,
};
const _PROJECT_LIST: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_project_list(handle: jlong, target_device_id: JString) -> JString,
    fn = native_project_list,
};
const _PROJECT_SET_PRIMARY_WORKSPACE: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_project_set_primary_workspace(handle: jlong, target_device_id: JString, project_id: JString, workspace_id: JString) -> JString,
    fn = native_project_set_primary_workspace,
};
const _POLL_AGENT_EVENTS: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_poll_agent_events(handle: jlong) -> JString,
    fn = native_poll_agent_events,
};
const _AGENT_EVENTS_RESUME: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_agent_events_resume(handle: jlong, target_device_id: JString, workspace_id: JString, after_sequence: jlong) -> JString,
    fn = native_agent_events_resume,
};
#[cfg(feature = "dev-passkey")]
const _DEV_PASSKEY_REGISTER: jni::NativeMethod = native_method! {
    java_type = "ai.choosh.NativeBridge",
    static extern fn NativeBridge::native_dev_passkey_register(origin: JString, creation_options_json: JString) -> JString,
    fn = native_dev_passkey_register,
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_handle_is_reported_not_panicked() {
        assert_eq!(with_handle(999_999, "absent".to_string(), |_| "present".to_string()), "absent");
    }

    #[test]
    fn handles_are_unique_and_monotonic() {
        let a = NEXT_HANDLE.fetch_add(1, Ordering::Relaxed);
        let b = NEXT_HANDLE.fetch_add(1, Ordering::Relaxed);
        assert!(b > a);
    }
}
